[modules]
left = ["Workspaces"]
center = [ "Clock" ]
right = [ "KeyboardLayout", "SystemInfo", [  "Tray", "Privacy", "Settings" ] ]

[appearance]
font_name = "Noto Sans"
style = "Solid"

primary_color = "#b4b7bf"
success_color = "#9ece6a"
text_color = "#B8B8B8"
workspace_colors = [ "#3B3E47", "#9ece6a" ]
special_workspace_colors = [ "#373737", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#2B2E37"
weak = "#3B3E47"
strong = "#5a5d66"

[appearance.secondary_color]
base = "#0c0d14"

[keyboard_layout.labels]
"English (US)" = "EN"
"Russian" = "RU"
"Kazakh" = "KZ"
